### ISSUE TITLE
LND says channel is active, LDK says it is not

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/react-native-ldk#238]
I'm opening a channel from LND to LDK (bitkit). LND api says channel is ready. LDK shows an error, but after refresh (probably syncLdk) it accepts the channel.

LDK logs:
```
LOG  LDK: INFO (LDK): Received channel_ready from peer for channel 0b544490a59427dfeef4a156f6d335a3c4a0e06ed6f57d8d3a41db41060f6df7 (lightning::ln::channel 3100)
...
 LOG  LDK: DEBUG (LDK): Received channel_update ChannelUpdate { signature: 3045022100e3364cef1d5f75792278d9e58990a648e088d1b074aa5d15e9794b3df78141e7022045082519b2fe8323c42a44c35fec1d233afbc93eb4cc848649380c77da0f24e5, contents: UnsignedChannelUpdate { chain_hash: 06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f, short_channel_id: 178120883765248, timestamp: 1715253241, flags: 1, cltv_expiry_delta: 80, htlc_minimum_msat: 1000, htlc_maximum_msat: 100000000, fee_base_msat: 1000, fee_proportional_millionths: 1, excess_data: [] } } for channel 0b544490a59427dfeef4a156f6d335a3c4a0e06ed6f57d8d3a41db41060f6df7. (lightning::ln::channelmanager 7111)
 LOG  LDK: DEBUG (LDK): Error handling message from 0367c93b620b8a1a664a2e5a3828f31e2b3977510ba69e2db6183f95a41c1230a2; ignoring: Couldn't find channel for update (lightning::ln::peer_handler 1518)
 LOG  react-native-ldk: Adding channel manager backup to queue
 LOG  LDK: DEBUG (LDK): Error handling message from 0367c93b620b8a1a664a2e5a3828f31e2b3977510ba69e2db6183f95a41c1230a2; ignoring: No existing channels for node_announcement (lightning::ln::peer_handler 1518)
 ```
 
 and after the refresh:
 ```
[
    {
        "balance_sat": 0,
        "channel_id": "0b544490a59427dfeef4a156f6d335a3c4a0e06ed6f57d8d3a41db41060f6df7",
        "channel_type": "401000",
        "channel_value_satoshis": 100000,
        "config_forwarding_fee_base_msat": 1000,
        "config_forwarding_fee_proportional_millionths": 0,
        "confirmations": 6,
        "confirmations_required": 1,
        "counterparty_node_id": "0367c93b620b8a1a664a2e5a3828f31e2b3977510ba69e2db6183f95a41c1230a2",
        "createdAt": 1715253231488,
        "force_close_spend_delay": 144,
        "funding_txid": "f76d0f0641db413a8d7df5d66ee0a0c4a335d3f656a1f4eedf2794a59044540b",
        "inbound_capacity_sat": 99000,
        "inbound_payment_scid": 178120883765248,
        "inbound_scid_alias": "178120883765248",
        "is_channel_ready": true,
        "is_outbound": false,
        "is_public": false,
        "is_usable": true,
        "outbound_capacity_sat": 0,
        "short_channel_id": "178120883765248",
        "status": "open",
        "unspendable_punishment_reserve": 1000,
        "user_channel_id": "2a310020a9880e86edbc5e873a351228"
    }
]
```

issue is reproducible in docker regtest enviroment using this config:
```

  lnd:
    image: lightninglabs/lnd:v0.16.2-beta
    container_name: lnd
    restart: always
    # network_mode: host
    volumes:
      - ./data/lnd:/home/lnd/.lnd
      - ./data/lnd:/root/.lnd
    expose:
      - '8080' # REST
      - '9735' # P2P
      - '10009' # RPC
    ports:
      - '8080:8080'
      - '9735:9735'
      - '10009:10009'
    command: --noseedbackup --nobootstrap --restlisten=0.0.0.0:8080 --debuglevel=debug --maxpendingchannels=10 --rpclisten=0.0.0.0:10009 --listen=0.0.0.0:9735 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=host.docker.internal:18443 --bitcoind.rpcuser=polaruser --bitcoind.rpcpass=polarpass --bitcoind.rpcpolling --protocol.wumbo-channels --debuglevel=debug --tlsextradomain=lnd
```
